begin;

create extension if not exists pgcrypto;

do $$
begin
  begin
    create extension if not exists pg_cron;
  exception
    when insufficient_privilege then
      raise notice 'Skipping pg_cron extension (insufficient privilege).';
    when undefined_file then
      raise notice 'Skipping pg_cron extension (not installed).';
  end;
end $$;

create table if not exists public.chat_profiles (
  mc_profile_id text primary key,
  owner_auth_uid uuid not null unique references auth.users(id) on delete cascade,
  mc_username text not null,
  avatar_url text,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create index if not exists chat_profiles_username_idx on public.chat_profiles (lower(mc_username));

create table if not exists public.chat_presence (
  mc_profile_id text primary key references public.chat_profiles(mc_profile_id) on delete cascade,
  is_online boolean not null default false,
  last_seen_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.chat_threads (
  id uuid primary key default gen_random_uuid(),
  kind text not null check (kind in ('group', 'dm')),
  title text,
  dm_member_a text references public.chat_profiles(mc_profile_id) on delete set null,
  dm_member_b text references public.chat_profiles(mc_profile_id) on delete set null,
  created_by_profile_id text not null references public.chat_profiles(mc_profile_id) on delete restrict,
  last_message_at timestamptz,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint chat_threads_kind_shape_check check (
    (kind = 'dm' and title is null and dm_member_a is not null and dm_member_b is not null and dm_member_a < dm_member_b)
    or
    (kind = 'group' and dm_member_a is null and dm_member_b is null and title is not null and char_length(btrim(title)) between 1 and 80)
  )
);

create unique index if not exists chat_threads_dm_pair_unique_idx
  on public.chat_threads (dm_member_a, dm_member_b)
  where kind = 'dm';

create index if not exists chat_threads_updated_at_idx on public.chat_threads (updated_at desc);
create index if not exists chat_threads_last_message_at_idx on public.chat_threads (last_message_at desc nulls last);

create table if not exists public.chat_thread_members (
  thread_id uuid not null references public.chat_threads(id) on delete cascade,
  member_profile_id text not null references public.chat_profiles(mc_profile_id) on delete cascade,
  role text not null default 'member' check (role in ('owner', 'member')),
  joined_at timestamptz not null default timezone('utc', now()),
  primary key (thread_id, member_profile_id)
);

create index if not exists chat_thread_members_member_idx on public.chat_thread_members (member_profile_id, thread_id);

create table if not exists public.chat_messages (
  id bigint generated by default as identity primary key,
  thread_id uuid not null references public.chat_threads(id) on delete cascade,
  sender_profile_id text not null references public.chat_profiles(mc_profile_id) on delete restrict,
  body text,
  reply_to_message_id bigint references public.chat_messages(id) on delete set null,
  edited_at timestamptz,
  deleted_at timestamptz,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint chat_messages_body_check check (
    (deleted_at is not null and body is null)
    or
    (deleted_at is null and body is not null and char_length(btrim(body)) between 1 and 2000)
  )
);

create index if not exists chat_messages_thread_id_id_idx on public.chat_messages (thread_id, id desc);
create index if not exists chat_messages_created_at_idx on public.chat_messages (created_at desc);

create table if not exists public.chat_message_reactions (
  message_id bigint not null references public.chat_messages(id) on delete cascade,
  profile_id text not null references public.chat_profiles(mc_profile_id) on delete cascade,
  reaction text not null check (char_length(btrim(reaction)) between 1 and 32),
  created_at timestamptz not null default timezone('utc', now()),
  primary key (message_id, profile_id, reaction)
);

create index if not exists chat_message_reactions_message_idx on public.chat_message_reactions (message_id);

create table if not exists public.chat_read_receipts (
  thread_id uuid not null references public.chat_threads(id) on delete cascade,
  profile_id text not null references public.chat_profiles(mc_profile_id) on delete cascade,
  last_read_message_id bigint references public.chat_messages(id) on delete set null,
  last_read_at timestamptz not null default timezone('utc', now()),
  primary key (thread_id, profile_id)
);

create table if not exists public.chat_typing_states (
  thread_id uuid not null references public.chat_threads(id) on delete cascade,
  profile_id text not null references public.chat_profiles(mc_profile_id) on delete cascade,
  typing_until timestamptz not null,
  updated_at timestamptz not null default timezone('utc', now()),
  primary key (thread_id, profile_id)
);

create index if not exists chat_typing_states_until_idx on public.chat_typing_states (typing_until);

create table if not exists public.chat_friendships (
  profile_low text not null references public.chat_profiles(mc_profile_id) on delete cascade,
  profile_high text not null references public.chat_profiles(mc_profile_id) on delete cascade,
  created_at timestamptz not null default timezone('utc', now()),
  constraint chat_friendships_pair_check check (profile_low < profile_high),
  primary key (profile_low, profile_high)
);

create table if not exists public.chat_friend_requests (
  id uuid primary key default gen_random_uuid(),
  sender_profile_id text not null references public.chat_profiles(mc_profile_id) on delete cascade,
  receiver_profile_id text not null references public.chat_profiles(mc_profile_id) on delete cascade,
  status text not null default 'pending' check (status in ('pending', 'accepted', 'declined', 'cancelled')),
  created_at timestamptz not null default timezone('utc', now()),
  responded_at timestamptz,
  constraint chat_friend_requests_self_check check (sender_profile_id <> receiver_profile_id)
);

create unique index if not exists chat_friend_requests_pending_pair_idx
  on public.chat_friend_requests (least(sender_profile_id, receiver_profile_id), greatest(sender_profile_id, receiver_profile_id))
  where status = 'pending';

create index if not exists chat_friend_requests_receiver_idx on public.chat_friend_requests (receiver_profile_id, status, created_at desc);
create index if not exists chat_friend_requests_sender_idx on public.chat_friend_requests (sender_profile_id, status, created_at desc);

create table if not exists public.chat_notifications (
  id bigint generated by default as identity primary key,
  profile_id text not null references public.chat_profiles(mc_profile_id) on delete cascade,
  type text not null,
  title text not null,
  body text,
  payload jsonb not null default '{}'::jsonb,
  read_at timestamptz,
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists chat_notifications_profile_idx on public.chat_notifications (profile_id, created_at desc);
create index if not exists chat_notifications_unread_idx on public.chat_notifications (profile_id, read_at) where read_at is null;

create or replace function public.chat_touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

drop trigger if exists trg_chat_profiles_touch_updated_at on public.chat_profiles;
create trigger trg_chat_profiles_touch_updated_at
before update on public.chat_profiles
for each row
execute procedure public.chat_touch_updated_at();

drop trigger if exists trg_chat_presence_touch_updated_at on public.chat_presence;
create trigger trg_chat_presence_touch_updated_at
before update on public.chat_presence
for each row
execute procedure public.chat_touch_updated_at();

drop trigger if exists trg_chat_threads_touch_updated_at on public.chat_threads;
create trigger trg_chat_threads_touch_updated_at
before update on public.chat_threads
for each row
execute procedure public.chat_touch_updated_at();

drop trigger if exists trg_chat_messages_touch_updated_at on public.chat_messages;
create trigger trg_chat_messages_touch_updated_at
before update on public.chat_messages
for each row
execute procedure public.chat_touch_updated_at();

drop trigger if exists trg_chat_typing_states_touch_updated_at on public.chat_typing_states;
create trigger trg_chat_typing_states_touch_updated_at
before update on public.chat_typing_states
for each row
execute procedure public.chat_touch_updated_at();

create or replace function public.chat_enforce_member_rules()
returns trigger
language plpgsql
as $$
declare
  thread_kind text;
  current_members integer;
begin
  select t.kind into thread_kind
  from public.chat_threads t
  where t.id = new.thread_id
  for update;

  if thread_kind is null then
    raise exception 'Thread not found.';
  end if;

  select count(*)::int into current_members
  from public.chat_thread_members tm
  where tm.thread_id = new.thread_id;

  if thread_kind = 'group' and current_members >= 10 then
    raise exception 'Group chat member limit reached (max 10).';
  end if;

  if thread_kind = 'dm' and current_members >= 2 then
    raise exception 'DM can only contain two members.';
  end if;

  return new;
end;
$$;

drop trigger if exists trg_chat_enforce_member_rules on public.chat_thread_members;
create trigger trg_chat_enforce_member_rules
before insert on public.chat_thread_members
for each row
execute procedure public.chat_enforce_member_rules();

create or replace function public.chat_validate_reply_target()
returns trigger
language plpgsql
as $$
declare
  reply_thread_id uuid;
begin
  if new.reply_to_message_id is null then
    return new;
  end if;

  select m.thread_id into reply_thread_id
  from public.chat_messages m
  where m.id = new.reply_to_message_id;

  if reply_thread_id is null then
    raise exception 'Reply target does not exist.';
  end if;

  if reply_thread_id <> new.thread_id then
    raise exception 'Reply target must be from the same thread.';
  end if;

  return new;
end;
$$;

drop trigger if exists trg_chat_validate_reply_target on public.chat_messages;
create trigger trg_chat_validate_reply_target
before insert or update of reply_to_message_id, thread_id on public.chat_messages
for each row
execute procedure public.chat_validate_reply_target();

create or replace function public.chat_refresh_thread_timestamps()
returns trigger
language plpgsql
as $$
declare
  affected_thread_id uuid;
  next_last_message_at timestamptz;
begin
  affected_thread_id := coalesce(new.thread_id, old.thread_id);

  select max(m.created_at) into next_last_message_at
  from public.chat_messages m
  where m.thread_id = affected_thread_id;

  update public.chat_threads t
  set
    last_message_at = next_last_message_at,
    updated_at = timezone('utc', now())
  where t.id = affected_thread_id;

  return coalesce(new, old);
end;
$$;

drop trigger if exists trg_chat_refresh_thread_timestamps on public.chat_messages;
create trigger trg_chat_refresh_thread_timestamps
after insert or update or delete on public.chat_messages
for each row
execute procedure public.chat_refresh_thread_timestamps();

create or replace function public.chat_validate_read_receipt()
returns trigger
language plpgsql
as $$
declare
  read_thread_id uuid;
begin
  if new.last_read_message_id is not null then
    select m.thread_id into read_thread_id
    from public.chat_messages m
    where m.id = new.last_read_message_id;

    if read_thread_id is null then
      raise exception 'Read receipt references a missing message.';
    end if;

    if read_thread_id <> new.thread_id then
      raise exception 'Read receipt message must belong to the same thread.';
    end if;
  end if;

  if tg_op = 'UPDATE' and old.last_read_message_id is not null and new.last_read_message_id is not null then
    if new.last_read_message_id < old.last_read_message_id then
      new.last_read_message_id := old.last_read_message_id;
    end if;
  end if;

  return new;
end;
$$;

drop trigger if exists trg_chat_validate_read_receipt on public.chat_read_receipts;
create trigger trg_chat_validate_read_receipt
before insert or update on public.chat_read_receipts
for each row
execute procedure public.chat_validate_read_receipt();

create or replace function public.chat_actor_profile_id()
returns text
language sql
stable
security definer
set search_path = public
as $$
  select cp.mc_profile_id
  from public.chat_profiles cp
  where cp.owner_auth_uid = auth.uid()
  limit 1
$$;

create or replace function public.chat_sync_identity(
  p_mc_profile_id text,
  p_mc_username text,
  p_avatar_url text default null
)
returns public.chat_profiles
language plpgsql
security definer
set search_path = public
as $$
declare
  current_uid uuid;
  existing_owner uuid;
  upserted_profile public.chat_profiles;
begin
  current_uid := auth.uid();
  if current_uid is null then
    raise exception 'Authentication required.';
  end if;

  if p_mc_profile_id is null or char_length(btrim(p_mc_profile_id)) = 0 then
    raise exception 'MC profile id is required.';
  end if;

  if p_mc_username is null or char_length(btrim(p_mc_username)) = 0 then
    raise exception 'MC username is required.';
  end if;

  select cp.owner_auth_uid into existing_owner
  from public.chat_profiles cp
  where cp.mc_profile_id = p_mc_profile_id
  limit 1;

  if existing_owner is not null and existing_owner <> current_uid then
    raise exception 'This Minecraft profile is already linked to a different account.';
  end if;

  insert into public.chat_profiles (mc_profile_id, owner_auth_uid, mc_username, avatar_url)
  values (p_mc_profile_id, current_uid, btrim(p_mc_username), nullif(btrim(p_avatar_url), ''))
  on conflict (owner_auth_uid) do update
  set
    mc_profile_id = excluded.mc_profile_id,
    mc_username = excluded.mc_username,
    avatar_url = excluded.avatar_url,
    updated_at = timezone('utc', now())
  returning * into upserted_profile;

  insert into public.chat_presence (mc_profile_id, is_online, last_seen_at)
  values (upserted_profile.mc_profile_id, true, timezone('utc', now()))
  on conflict (mc_profile_id) do update
  set
    is_online = true,
    last_seen_at = timezone('utc', now()),
    updated_at = timezone('utc', now());

  return upserted_profile;
end;
$$;

create or replace function public.chat_set_presence(p_is_online boolean)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  actor_profile_id text;
begin
  actor_profile_id := public.chat_actor_profile_id();
  if actor_profile_id is null then
    return;
  end if;

  insert into public.chat_presence (mc_profile_id, is_online, last_seen_at)
  values (actor_profile_id, coalesce(p_is_online, false), timezone('utc', now()))
  on conflict (mc_profile_id) do update
  set
    is_online = coalesce(p_is_online, false),
    last_seen_at = timezone('utc', now()),
    updated_at = timezone('utc', now());
end;
$$;

create or replace function public.chat_search_profiles(p_query text, p_limit integer default 20)
returns table (
  mc_profile_id text,
  mc_username text,
  avatar_url text,
  is_online boolean,
  last_seen_at timestamptz
)
language plpgsql
security definer
set search_path = public
as $$
declare
  actor_profile_id text;
  normalized_query text;
  safe_limit integer;
begin
  actor_profile_id := public.chat_actor_profile_id();
  if actor_profile_id is null then
    raise exception 'Chat identity not synced.';
  end if;

  normalized_query := coalesce(btrim(p_query), '');
  safe_limit := greatest(1, least(coalesce(p_limit, 20), 50));

  return query
  select
    cp.mc_profile_id,
    cp.mc_username,
    cp.avatar_url,
    coalesce(pr.is_online, false) as is_online,
    pr.last_seen_at
  from public.chat_profiles cp
  left join public.chat_presence pr on pr.mc_profile_id = cp.mc_profile_id
  where cp.mc_profile_id <> actor_profile_id
    and (
      normalized_query = ''
      or cp.mc_username ilike normalized_query || '%'
      or cp.mc_username ilike '%' || normalized_query || '%'
    )
  order by
    case when cp.mc_username ilike normalized_query || '%' then 0 else 1 end,
    lower(cp.mc_username)
  limit safe_limit;
end;
$$;

create or replace function public.chat_create_dm(p_target_profile_id text)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  actor_profile_id text;
  target_profile_id text;
  pair_a text;
  pair_b text;
  existing_thread_id uuid;
  created_thread_id uuid;
begin
  actor_profile_id := public.chat_actor_profile_id();
  if actor_profile_id is null then
    raise exception 'Chat identity not synced.';
  end if;

  target_profile_id := nullif(btrim(p_target_profile_id), '');
  if target_profile_id is null then
    raise exception 'Target profile is required.';
  end if;

  if actor_profile_id = target_profile_id then
    raise exception 'Cannot create a DM with yourself.';
  end if;

  if not exists (
    select 1 from public.chat_profiles cp where cp.mc_profile_id = target_profile_id
  ) then
    raise exception 'Target profile does not exist.';
  end if;

  pair_a := least(actor_profile_id, target_profile_id);
  pair_b := greatest(actor_profile_id, target_profile_id);

  select t.id into existing_thread_id
  from public.chat_threads t
  where t.kind = 'dm'
    and t.dm_member_a = pair_a
    and t.dm_member_b = pair_b
  limit 1;

  if existing_thread_id is not null then
    return existing_thread_id;
  end if;

  insert into public.chat_threads (kind, title, dm_member_a, dm_member_b, created_by_profile_id)
  values ('dm', null, pair_a, pair_b, actor_profile_id)
  returning id into created_thread_id;

  insert into public.chat_thread_members (thread_id, member_profile_id, role)
  values
    (created_thread_id, actor_profile_id, 'owner'),
    (created_thread_id, target_profile_id, 'member')
  on conflict do nothing;

  return created_thread_id;
end;
$$;

create or replace function public.chat_create_group(p_title text, p_member_profile_ids text[])
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  actor_profile_id text;
  normalized_title text;
  unique_members text[];
  all_members text[];
  known_member_count integer;
  created_thread_id uuid;
begin
  actor_profile_id := public.chat_actor_profile_id();
  if actor_profile_id is null then
    raise exception 'Chat identity not synced.';
  end if;

  normalized_title := btrim(coalesce(p_title, ''));
  if char_length(normalized_title) < 1 or char_length(normalized_title) > 80 then
    raise exception 'Group title must be between 1 and 80 characters.';
  end if;

  select coalesce(array_agg(distinct btrim(x)), '{}') into unique_members
  from unnest(coalesce(p_member_profile_ids, '{}')) as x
  where btrim(x) <> ''
    and btrim(x) <> actor_profile_id;

  all_members := array_prepend(actor_profile_id, unique_members);

  if cardinality(all_members) < 2 then
    raise exception 'A group chat must include at least two members.';
  end if;

  if cardinality(all_members) > 10 then
    raise exception 'Group chat member limit reached (max 10).';
  end if;

  select count(*)::int into known_member_count
  from public.chat_profiles cp
  where cp.mc_profile_id = any(all_members);

  if known_member_count <> cardinality(all_members) then
    raise exception 'One or more selected members do not exist.';
  end if;

  insert into public.chat_threads (kind, title, created_by_profile_id)
  values ('group', normalized_title, actor_profile_id)
  returning id into created_thread_id;

  insert into public.chat_thread_members (thread_id, member_profile_id, role)
  select
    created_thread_id,
    member_id,
    case when member_id = actor_profile_id then 'owner' else 'member' end
  from unnest(all_members) as member_id;

  return created_thread_id;
end;
$$;

create or replace function public.chat_list_threads()
returns table (
  thread_id uuid,
  kind text,
  title text,
  dm_other_profile_id text,
  dm_other_username text,
  dm_other_avatar_url text,
  member_count integer,
  last_message_id bigint,
  last_message_body text,
  last_message_sender_profile_id text,
  last_message_created_at timestamptz,
  last_message_deleted_at timestamptz,
  last_read_message_id bigint,
  unread_count integer,
  updated_at timestamptz
)
language plpgsql
security definer
set search_path = public
as $$
declare
  actor_profile_id text;
begin
  actor_profile_id := public.chat_actor_profile_id();
  if actor_profile_id is null then
    raise exception 'Chat identity not synced.';
  end if;

  return query
  with actor_threads as (
    select tm.thread_id
    from public.chat_thread_members tm
    where tm.member_profile_id = actor_profile_id
  )
  select
    t.id as thread_id,
    t.kind,
    t.title,
    case when t.kind = 'dm' then other_profile.mc_profile_id else null end as dm_other_profile_id,
    case when t.kind = 'dm' then other_profile.mc_username else null end as dm_other_username,
    case when t.kind = 'dm' then other_profile.avatar_url else null end as dm_other_avatar_url,
    member_stats.member_count,
    lm.id as last_message_id,
    lm.body as last_message_body,
    lm.sender_profile_id as last_message_sender_profile_id,
    lm.created_at as last_message_created_at,
    lm.deleted_at as last_message_deleted_at,
    rr.last_read_message_id,
    coalesce((
      select count(*)::int
      from public.chat_messages unread
      where unread.thread_id = t.id
        and unread.id > coalesce(rr.last_read_message_id, 0)
        and unread.sender_profile_id <> actor_profile_id
        and unread.deleted_at is null
    ), 0) as unread_count,
    t.updated_at
  from actor_threads at
  join public.chat_threads t on t.id = at.thread_id
  left join lateral (
    select cp.mc_profile_id, cp.mc_username, cp.avatar_url
    from public.chat_thread_members tm
    join public.chat_profiles cp on cp.mc_profile_id = tm.member_profile_id
    where tm.thread_id = t.id
      and tm.member_profile_id <> actor_profile_id
    order by tm.joined_at asc
    limit 1
  ) other_profile on true
  left join lateral (
    select count(*)::int as member_count
    from public.chat_thread_members tm
    where tm.thread_id = t.id
  ) member_stats on true
  left join lateral (
    select
      m.id,
      m.body,
      m.sender_profile_id,
      m.created_at,
      m.deleted_at
    from public.chat_messages m
    where m.thread_id = t.id
      and m.created_at >= timezone('utc', now()) - interval '30 days'
    order by m.id desc
    limit 1
  ) lm on true
  left join public.chat_read_receipts rr
    on rr.thread_id = t.id
   and rr.profile_id = actor_profile_id
  order by coalesce(lm.created_at, t.updated_at) desc;
end;
$$;

create or replace function public.chat_list_messages(p_thread_id uuid, p_limit integer default 200)
returns table (
  id bigint,
  thread_id uuid,
  sender_profile_id text,
  sender_username text,
  sender_avatar_url text,
  body text,
  reply_to_message_id bigint,
  reply_body text,
  reply_sender_profile_id text,
  reply_sender_username text,
  edited_at timestamptz,
  deleted_at timestamptz,
  created_at timestamptz,
  updated_at timestamptz
)
language plpgsql
security definer
set search_path = public
as $$
declare
  actor_profile_id text;
  safe_limit integer;
begin
  actor_profile_id := public.chat_actor_profile_id();
  if actor_profile_id is null then
    raise exception 'Chat identity not synced.';
  end if;

  if not exists (
    select 1
    from public.chat_thread_members tm
    where tm.thread_id = p_thread_id
      and tm.member_profile_id = actor_profile_id
  ) then
    raise exception 'Not authorized for this thread.';
  end if;

  safe_limit := greatest(1, least(coalesce(p_limit, 200), 300));

  return query
  select
    m.id,
    m.thread_id,
    m.sender_profile_id,
    sender.mc_username as sender_username,
    sender.avatar_url as sender_avatar_url,
    m.body,
    m.reply_to_message_id,
    reply_msg.body as reply_body,
    reply_msg.sender_profile_id as reply_sender_profile_id,
    reply_sender.mc_username as reply_sender_username,
    m.edited_at,
    m.deleted_at,
    m.created_at,
    m.updated_at
  from public.chat_messages m
  join public.chat_profiles sender on sender.mc_profile_id = m.sender_profile_id
  left join public.chat_messages reply_msg on reply_msg.id = m.reply_to_message_id
  left join public.chat_profiles reply_sender on reply_sender.mc_profile_id = reply_msg.sender_profile_id
  where m.thread_id = p_thread_id
    and m.created_at >= timezone('utc', now()) - interval '30 days'
  order by m.id desc
  limit safe_limit;
end;
$$;

create or replace function public.chat_list_members(p_thread_id uuid)
returns table (
  profile_id text,
  mc_username text,
  avatar_url text,
  role text,
  is_online boolean,
  last_seen_at timestamptz,
  last_read_message_id bigint,
  last_read_at timestamptz
)
language plpgsql
security definer
set search_path = public
as $$
declare
  actor_profile_id text;
begin
  actor_profile_id := public.chat_actor_profile_id();
  if actor_profile_id is null then
    raise exception 'Chat identity not synced.';
  end if;

  if not exists (
    select 1
    from public.chat_thread_members tm
    where tm.thread_id = p_thread_id
      and tm.member_profile_id = actor_profile_id
  ) then
    raise exception 'Not authorized for this thread.';
  end if;

  return query
  select
    tm.member_profile_id as profile_id,
    cp.mc_username,
    cp.avatar_url,
    tm.role,
    coalesce(pr.is_online, false) as is_online,
    pr.last_seen_at,
    rr.last_read_message_id,
    rr.last_read_at
  from public.chat_thread_members tm
  join public.chat_profiles cp on cp.mc_profile_id = tm.member_profile_id
  left join public.chat_presence pr on pr.mc_profile_id = tm.member_profile_id
  left join public.chat_read_receipts rr
    on rr.thread_id = tm.thread_id
   and rr.profile_id = tm.member_profile_id
  where tm.thread_id = p_thread_id
  order by
    case when tm.member_profile_id = actor_profile_id then 0 else 1 end,
    lower(cp.mc_username);
end;
$$;

create or replace function public.chat_list_reactions(p_thread_id uuid)
returns table (
  message_id bigint,
  profile_id text,
  mc_username text,
  avatar_url text,
  reaction text,
  created_at timestamptz
)
language plpgsql
security definer
set search_path = public
as $$
declare
  actor_profile_id text;
begin
  actor_profile_id := public.chat_actor_profile_id();
  if actor_profile_id is null then
    raise exception 'Chat identity not synced.';
  end if;

  if not exists (
    select 1
    from public.chat_thread_members tm
    where tm.thread_id = p_thread_id
      and tm.member_profile_id = actor_profile_id
  ) then
    raise exception 'Not authorized for this thread.';
  end if;

  return query
  select
    r.message_id,
    r.profile_id,
    cp.mc_username,
    cp.avatar_url,
    r.reaction,
    r.created_at
  from public.chat_message_reactions r
  join public.chat_messages m on m.id = r.message_id
  join public.chat_profiles cp on cp.mc_profile_id = r.profile_id
  where m.thread_id = p_thread_id
    and m.created_at >= timezone('utc', now()) - interval '30 days'
  order by r.created_at asc;
end;
$$;

create or replace function public.chat_list_typing(p_thread_id uuid)
returns table (
  profile_id text,
  mc_username text,
  typing_until timestamptz
)
language plpgsql
security definer
set search_path = public
as $$
declare
  actor_profile_id text;
begin
  actor_profile_id := public.chat_actor_profile_id();
  if actor_profile_id is null then
    raise exception 'Chat identity not synced.';
  end if;

  if not exists (
    select 1
    from public.chat_thread_members tm
    where tm.thread_id = p_thread_id
      and tm.member_profile_id = actor_profile_id
  ) then
    raise exception 'Not authorized for this thread.';
  end if;

  return query
  select
    ts.profile_id,
    cp.mc_username,
    ts.typing_until
  from public.chat_typing_states ts
  join public.chat_profiles cp on cp.mc_profile_id = ts.profile_id
  where ts.thread_id = p_thread_id
    and ts.profile_id <> actor_profile_id
    and ts.typing_until > timezone('utc', now())
  order by ts.typing_until desc;
end;
$$;

create or replace function public.chat_mark_thread_read(p_thread_id uuid, p_message_id bigint default null)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  actor_profile_id text;
  resolved_message_id bigint;
begin
  actor_profile_id := public.chat_actor_profile_id();
  if actor_profile_id is null then
    raise exception 'Chat identity not synced.';
  end if;

  if not exists (
    select 1
    from public.chat_thread_members tm
    where tm.thread_id = p_thread_id
      and tm.member_profile_id = actor_profile_id
  ) then
    raise exception 'Not authorized for this thread.';
  end if;

  if p_message_id is null then
    select max(m.id) into resolved_message_id
    from public.chat_messages m
    where m.thread_id = p_thread_id;
  else
    resolved_message_id := p_message_id;
  end if;

  if resolved_message_id is null then
    return;
  end if;

  if not exists (
    select 1
    from public.chat_messages m
    where m.id = resolved_message_id
      and m.thread_id = p_thread_id
  ) then
    raise exception 'Message is not part of this thread.';
  end if;

  insert into public.chat_read_receipts (thread_id, profile_id, last_read_message_id, last_read_at)
  values (p_thread_id, actor_profile_id, resolved_message_id, timezone('utc', now()))
  on conflict (thread_id, profile_id) do update
  set
    last_read_message_id = greatest(coalesce(public.chat_read_receipts.last_read_message_id, 0), excluded.last_read_message_id),
    last_read_at = timezone('utc', now());
end;
$$;

create or replace function public.chat_set_typing(p_thread_id uuid, p_is_typing boolean)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  actor_profile_id text;
begin
  actor_profile_id := public.chat_actor_profile_id();
  if actor_profile_id is null then
    raise exception 'Chat identity not synced.';
  end if;

  if not exists (
    select 1
    from public.chat_thread_members tm
    where tm.thread_id = p_thread_id
      and tm.member_profile_id = actor_profile_id
  ) then
    raise exception 'Not authorized for this thread.';
  end if;

  if coalesce(p_is_typing, false) then
    insert into public.chat_typing_states (thread_id, profile_id, typing_until)
    values (p_thread_id, actor_profile_id, timezone('utc', now()) + interval '8 seconds')
    on conflict (thread_id, profile_id) do update
    set
      typing_until = excluded.typing_until,
      updated_at = timezone('utc', now());
  else
    delete from public.chat_typing_states ts
    where ts.thread_id = p_thread_id
      and ts.profile_id = actor_profile_id;
  end if;
end;
$$;

create or replace function public.chat_run_maintenance()
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  delete from public.chat_typing_states ts
  where ts.typing_until < timezone('utc', now());

  delete from public.chat_messages m
  where m.created_at < timezone('utc', now()) - interval '30 days';

  update public.chat_presence p
  set
    is_online = false,
    updated_at = timezone('utc', now())
  where p.is_online = true
    and p.last_seen_at < timezone('utc', now()) - interval '2 minutes';

  delete from public.chat_notifications n
  where n.created_at < timezone('utc', now()) - interval '45 days';
end;
$$;

create or replace function public.chat_send_friend_request(p_target_profile_id text)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  actor_profile_id text;
  target_profile_id text;
  pair_low text;
  pair_high text;
  existing_pending_id uuid;
  request_id uuid;
begin
  actor_profile_id := public.chat_actor_profile_id();
  if actor_profile_id is null then
    raise exception 'Chat identity not synced.';
  end if;

  target_profile_id := nullif(btrim(p_target_profile_id), '');
  if target_profile_id is null then
    raise exception 'Target profile is required.';
  end if;

  if target_profile_id = actor_profile_id then
    raise exception 'You cannot friend yourself.';
  end if;

  if not exists (select 1 from public.chat_profiles cp where cp.mc_profile_id = target_profile_id) then
    raise exception 'Target profile does not exist.';
  end if;

  pair_low := least(actor_profile_id, target_profile_id);
  pair_high := greatest(actor_profile_id, target_profile_id);

  if exists (
    select 1 from public.chat_friendships f
    where f.profile_low = pair_low and f.profile_high = pair_high
  ) then
    raise exception 'Already friends.';
  end if;

  select fr.id into existing_pending_id
  from public.chat_friend_requests fr
  where fr.status = 'pending'
    and least(fr.sender_profile_id, fr.receiver_profile_id) = pair_low
    and greatest(fr.sender_profile_id, fr.receiver_profile_id) = pair_high
  limit 1;

  if existing_pending_id is not null then
    return existing_pending_id;
  end if;

  insert into public.chat_friend_requests (sender_profile_id, receiver_profile_id)
  values (actor_profile_id, target_profile_id)
  returning id into request_id;

  insert into public.chat_notifications (profile_id, type, title, body, payload)
  select
    target_profile_id,
    'friend_request',
    'Friend request',
    cp.mc_username || ' sent you a friend request.',
    jsonb_build_object(
      'request_id', request_id,
      'sender_profile_id', actor_profile_id,
      'sender_username', cp.mc_username
    )
  from public.chat_profiles cp
  where cp.mc_profile_id = actor_profile_id;

  return request_id;
end;
$$;

create or replace function public.chat_respond_friend_request(p_request_id uuid, p_action text)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  actor_profile_id text;
  req public.chat_friend_requests;
  next_status text;
  pair_low text;
  pair_high text;
begin
  actor_profile_id := public.chat_actor_profile_id();
  if actor_profile_id is null then
    raise exception 'Chat identity not synced.';
  end if;

  next_status := lower(coalesce(p_action, ''));
  if next_status not in ('accepted', 'declined') then
    raise exception 'Action must be accepted or declined.';
  end if;

  select * into req
  from public.chat_friend_requests fr
  where fr.id = p_request_id
  for update;

  if req.id is null then
    raise exception 'Friend request not found.';
  end if;

  if req.receiver_profile_id <> actor_profile_id then
    raise exception 'Not allowed to respond to this request.';
  end if;

  if req.status <> 'pending' then
    return;
  end if;

  update public.chat_friend_requests fr
  set
    status = next_status,
    responded_at = timezone('utc', now())
  where fr.id = req.id;

  if next_status = 'accepted' then
    pair_low := least(req.sender_profile_id, req.receiver_profile_id);
    pair_high := greatest(req.sender_profile_id, req.receiver_profile_id);
    insert into public.chat_friendships (profile_low, profile_high)
    values (pair_low, pair_high)
    on conflict do nothing;
  end if;

  insert into public.chat_notifications (profile_id, type, title, body, payload)
  select
    req.sender_profile_id,
    'friend_request_' || next_status,
    'Friend request ' || next_status,
    cp.mc_username || ' ' || case when next_status = 'accepted' then 'accepted' else 'declined' end || ' your friend request.',
    jsonb_build_object(
      'request_id', req.id,
      'receiver_profile_id', req.receiver_profile_id,
      'receiver_username', cp.mc_username,
      'status', next_status
    )
  from public.chat_profiles cp
  where cp.mc_profile_id = req.receiver_profile_id;
end;
$$;

create or replace function public.chat_list_friend_requests()
returns table (
  request_id uuid,
  sender_profile_id text,
  sender_username text,
  sender_avatar_url text,
  receiver_profile_id text,
  receiver_username text,
  receiver_avatar_url text,
  status text,
  created_at timestamptz,
  responded_at timestamptz,
  direction text
)
language plpgsql
security definer
set search_path = public
as $$
declare
  actor_profile_id text;
begin
  actor_profile_id := public.chat_actor_profile_id();
  if actor_profile_id is null then
    raise exception 'Chat identity not synced.';
  end if;

  return query
  select
    fr.id as request_id,
    fr.sender_profile_id,
    sender.mc_username as sender_username,
    sender.avatar_url as sender_avatar_url,
    fr.receiver_profile_id,
    receiver.mc_username as receiver_username,
    receiver.avatar_url as receiver_avatar_url,
    fr.status,
    fr.created_at,
    fr.responded_at,
    case when fr.receiver_profile_id = actor_profile_id then 'incoming' else 'outgoing' end as direction
  from public.chat_friend_requests fr
  join public.chat_profiles sender on sender.mc_profile_id = fr.sender_profile_id
  join public.chat_profiles receiver on receiver.mc_profile_id = fr.receiver_profile_id
  where fr.sender_profile_id = actor_profile_id or fr.receiver_profile_id = actor_profile_id
  order by fr.created_at desc;
end;
$$;

create or replace function public.chat_list_friends()
returns table (
  profile_id text,
  mc_username text,
  avatar_url text,
  is_online boolean,
  last_seen_at timestamptz,
  since timestamptz
)
language plpgsql
security definer
set search_path = public
as $$
declare
  actor_profile_id text;
begin
  actor_profile_id := public.chat_actor_profile_id();
  if actor_profile_id is null then
    raise exception 'Chat identity not synced.';
  end if;

  return query
  select
    friend.cp_id as profile_id,
    cp.mc_username,
    cp.avatar_url,
    coalesce(pr.is_online, false) as is_online,
    pr.last_seen_at,
    friend.created_at as since
  from (
    select
      case when f.profile_low = actor_profile_id then f.profile_high else f.profile_low end as cp_id,
      f.created_at
    from public.chat_friendships f
    where f.profile_low = actor_profile_id or f.profile_high = actor_profile_id
  ) friend
  join public.chat_profiles cp on cp.mc_profile_id = friend.cp_id
  left join public.chat_presence pr on pr.mc_profile_id = friend.cp_id
  order by lower(cp.mc_username);
end;
$$;

create or replace function public.chat_list_notifications(p_limit integer default 30)
returns table (
  id bigint,
  type text,
  title text,
  body text,
  payload jsonb,
  created_at timestamptz,
  read_at timestamptz
)
language plpgsql
security definer
set search_path = public
as $$
declare
  actor_profile_id text;
  safe_limit integer;
begin
  actor_profile_id := public.chat_actor_profile_id();
  if actor_profile_id is null then
    raise exception 'Chat identity not synced.';
  end if;

  safe_limit := greatest(1, least(coalesce(p_limit, 30), 100));

  return query
  select n.id, n.type, n.title, n.body, n.payload, n.created_at, n.read_at
  from public.chat_notifications n
  where n.profile_id = actor_profile_id
  order by n.created_at desc
  limit safe_limit;
end;
$$;

create or replace function public.chat_mark_notifications_read(p_notification_id bigint default null)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  actor_profile_id text;
begin
  actor_profile_id := public.chat_actor_profile_id();
  if actor_profile_id is null then
    raise exception 'Chat identity not synced.';
  end if;

  if p_notification_id is null then
    update public.chat_notifications n
    set read_at = timezone('utc', now())
    where n.profile_id = actor_profile_id
      and n.read_at is null;
  else
    update public.chat_notifications n
    set read_at = timezone('utc', now())
    where n.profile_id = actor_profile_id
      and n.id = p_notification_id
      and n.read_at is null;
  end if;
end;
$$;

alter table public.chat_profiles enable row level security;
alter table public.chat_presence enable row level security;
alter table public.chat_threads enable row level security;
alter table public.chat_thread_members enable row level security;
alter table public.chat_messages enable row level security;
alter table public.chat_message_reactions enable row level security;
alter table public.chat_read_receipts enable row level security;
alter table public.chat_typing_states enable row level security;
alter table public.chat_friendships enable row level security;
alter table public.chat_friend_requests enable row level security;
alter table public.chat_notifications enable row level security;

drop policy if exists chat_profiles_select_authenticated on public.chat_profiles;
create policy chat_profiles_select_authenticated
  on public.chat_profiles
  for select
  to authenticated
  using (true);

drop policy if exists chat_profiles_insert_own on public.chat_profiles;
create policy chat_profiles_insert_own
  on public.chat_profiles
  for insert
  to authenticated
  with check (owner_auth_uid = auth.uid());

drop policy if exists chat_profiles_update_own on public.chat_profiles;
create policy chat_profiles_update_own
  on public.chat_profiles
  for update
  to authenticated
  using (owner_auth_uid = auth.uid())
  with check (owner_auth_uid = auth.uid());

drop policy if exists chat_presence_select_authenticated on public.chat_presence;
create policy chat_presence_select_authenticated
  on public.chat_presence
  for select
  to authenticated
  using (true);

drop policy if exists chat_presence_insert_own on public.chat_presence;
create policy chat_presence_insert_own
  on public.chat_presence
  for insert
  to authenticated
  with check (
    exists (
      select 1
      from public.chat_profiles cp
      where cp.mc_profile_id = chat_presence.mc_profile_id
        and cp.owner_auth_uid = auth.uid()
    )
  );

drop policy if exists chat_presence_update_own on public.chat_presence;
create policy chat_presence_update_own
  on public.chat_presence
  for update
  to authenticated
  using (
    exists (
      select 1
      from public.chat_profiles cp
      where cp.mc_profile_id = chat_presence.mc_profile_id
        and cp.owner_auth_uid = auth.uid()
    )
  )
  with check (
    exists (
      select 1
      from public.chat_profiles cp
      where cp.mc_profile_id = chat_presence.mc_profile_id
        and cp.owner_auth_uid = auth.uid()
    )
  );

drop policy if exists chat_threads_select_member on public.chat_threads;
create policy chat_threads_select_member
  on public.chat_threads
  for select
  to authenticated
  using (
    exists (
      select 1
      from public.chat_thread_members tm
      join public.chat_profiles cp on cp.mc_profile_id = tm.member_profile_id
      where tm.thread_id = chat_threads.id
        and cp.owner_auth_uid = auth.uid()
    )
  );

drop policy if exists chat_thread_members_select_member on public.chat_thread_members;
create policy chat_thread_members_select_member
  on public.chat_thread_members
  for select
  to authenticated
  using (
    exists (
      select 1
      from public.chat_thread_members my_tm
      join public.chat_profiles cp on cp.mc_profile_id = my_tm.member_profile_id
      where my_tm.thread_id = chat_thread_members.thread_id
        and cp.owner_auth_uid = auth.uid()
    )
  );

drop policy if exists chat_messages_select_member on public.chat_messages;
create policy chat_messages_select_member
  on public.chat_messages
  for select
  to authenticated
  using (
    exists (
      select 1
      from public.chat_thread_members tm
      join public.chat_profiles cp on cp.mc_profile_id = tm.member_profile_id
      where tm.thread_id = chat_messages.thread_id
        and cp.owner_auth_uid = auth.uid()
    )
  );

drop policy if exists chat_messages_insert_sender on public.chat_messages;
create policy chat_messages_insert_sender
  on public.chat_messages
  for insert
  to authenticated
  with check (
    exists (
      select 1
      from public.chat_profiles cp
      where cp.mc_profile_id = chat_messages.sender_profile_id
        and cp.owner_auth_uid = auth.uid()
    )
    and exists (
      select 1
      from public.chat_thread_members tm
      where tm.thread_id = chat_messages.thread_id
        and tm.member_profile_id = chat_messages.sender_profile_id
    )
  );

drop policy if exists chat_messages_update_sender on public.chat_messages;
create policy chat_messages_update_sender
  on public.chat_messages
  for update
  to authenticated
  using (
    exists (
      select 1
      from public.chat_profiles cp
      where cp.mc_profile_id = chat_messages.sender_profile_id
        and cp.owner_auth_uid = auth.uid()
    )
    and exists (
      select 1
      from public.chat_thread_members tm
      where tm.thread_id = chat_messages.thread_id
        and tm.member_profile_id = chat_messages.sender_profile_id
    )
  )
  with check (
    exists (
      select 1
      from public.chat_profiles cp
      where cp.mc_profile_id = chat_messages.sender_profile_id
        and cp.owner_auth_uid = auth.uid()
    )
    and exists (
      select 1
      from public.chat_thread_members tm
      where tm.thread_id = chat_messages.thread_id
        and tm.member_profile_id = chat_messages.sender_profile_id
    )
  );

drop policy if exists chat_message_reactions_select_member on public.chat_message_reactions;
create policy chat_message_reactions_select_member
  on public.chat_message_reactions
  for select
  to authenticated
  using (
    exists (
      select 1
      from public.chat_messages m
      join public.chat_thread_members tm on tm.thread_id = m.thread_id
      join public.chat_profiles cp on cp.mc_profile_id = tm.member_profile_id
      where m.id = chat_message_reactions.message_id
        and cp.owner_auth_uid = auth.uid()
    )
  );

drop policy if exists chat_message_reactions_insert_own on public.chat_message_reactions;
create policy chat_message_reactions_insert_own
  on public.chat_message_reactions
  for insert
  to authenticated
  with check (
    exists (
      select 1
      from public.chat_profiles cp
      where cp.mc_profile_id = chat_message_reactions.profile_id
        and cp.owner_auth_uid = auth.uid()
    )
    and exists (
      select 1
      from public.chat_messages m
      join public.chat_thread_members tm on tm.thread_id = m.thread_id
      where m.id = chat_message_reactions.message_id
        and tm.member_profile_id = chat_message_reactions.profile_id
    )
  );

drop policy if exists chat_message_reactions_delete_own on public.chat_message_reactions;
create policy chat_message_reactions_delete_own
  on public.chat_message_reactions
  for delete
  to authenticated
  using (
    exists (
      select 1
      from public.chat_profiles cp
      where cp.mc_profile_id = chat_message_reactions.profile_id
        and cp.owner_auth_uid = auth.uid()
    )
  );

drop policy if exists chat_read_receipts_select_member on public.chat_read_receipts;
create policy chat_read_receipts_select_member
  on public.chat_read_receipts
  for select
  to authenticated
  using (
    exists (
      select 1
      from public.chat_thread_members tm
      join public.chat_profiles cp on cp.mc_profile_id = tm.member_profile_id
      where tm.thread_id = chat_read_receipts.thread_id
        and cp.owner_auth_uid = auth.uid()
    )
  );

drop policy if exists chat_read_receipts_insert_own on public.chat_read_receipts;
create policy chat_read_receipts_insert_own
  on public.chat_read_receipts
  for insert
  to authenticated
  with check (
    exists (
      select 1
      from public.chat_profiles cp
      where cp.mc_profile_id = chat_read_receipts.profile_id
        and cp.owner_auth_uid = auth.uid()
    )
    and exists (
      select 1
      from public.chat_thread_members tm
      where tm.thread_id = chat_read_receipts.thread_id
        and tm.member_profile_id = chat_read_receipts.profile_id
    )
  );

drop policy if exists chat_read_receipts_update_own on public.chat_read_receipts;
create policy chat_read_receipts_update_own
  on public.chat_read_receipts
  for update
  to authenticated
  using (
    exists (
      select 1
      from public.chat_profiles cp
      where cp.mc_profile_id = chat_read_receipts.profile_id
        and cp.owner_auth_uid = auth.uid()
    )
  )
  with check (
    exists (
      select 1
      from public.chat_profiles cp
      where cp.mc_profile_id = chat_read_receipts.profile_id
        and cp.owner_auth_uid = auth.uid()
    )
    and exists (
      select 1
      from public.chat_thread_members tm
      where tm.thread_id = chat_read_receipts.thread_id
        and tm.member_profile_id = chat_read_receipts.profile_id
    )
  );

drop policy if exists chat_typing_states_select_member on public.chat_typing_states;
create policy chat_typing_states_select_member
  on public.chat_typing_states
  for select
  to authenticated
  using (
    exists (
      select 1
      from public.chat_thread_members tm
      join public.chat_profiles cp on cp.mc_profile_id = tm.member_profile_id
      where tm.thread_id = chat_typing_states.thread_id
        and cp.owner_auth_uid = auth.uid()
    )
  );

drop policy if exists chat_typing_states_insert_own on public.chat_typing_states;
create policy chat_typing_states_insert_own
  on public.chat_typing_states
  for insert
  to authenticated
  with check (
    exists (
      select 1
      from public.chat_profiles cp
      where cp.mc_profile_id = chat_typing_states.profile_id
        and cp.owner_auth_uid = auth.uid()
    )
    and exists (
      select 1
      from public.chat_thread_members tm
      where tm.thread_id = chat_typing_states.thread_id
        and tm.member_profile_id = chat_typing_states.profile_id
    )
  );

drop policy if exists chat_typing_states_update_own on public.chat_typing_states;
create policy chat_typing_states_update_own
  on public.chat_typing_states
  for update
  to authenticated
  using (
    exists (
      select 1
      from public.chat_profiles cp
      where cp.mc_profile_id = chat_typing_states.profile_id
        and cp.owner_auth_uid = auth.uid()
    )
  )
  with check (
    exists (
      select 1
      from public.chat_profiles cp
      where cp.mc_profile_id = chat_typing_states.profile_id
        and cp.owner_auth_uid = auth.uid()
    )
    and exists (
      select 1
      from public.chat_thread_members tm
      where tm.thread_id = chat_typing_states.thread_id
        and tm.member_profile_id = chat_typing_states.profile_id
    )
  );

drop policy if exists chat_typing_states_delete_own on public.chat_typing_states;
create policy chat_typing_states_delete_own
  on public.chat_typing_states
  for delete
  to authenticated
  using (
    exists (
      select 1
      from public.chat_profiles cp
      where cp.mc_profile_id = chat_typing_states.profile_id
        and cp.owner_auth_uid = auth.uid()
    )
  );

drop policy if exists chat_friendships_select_member on public.chat_friendships;
create policy chat_friendships_select_member
  on public.chat_friendships
  for select
  to authenticated
  using (
    exists (
      select 1
      from public.chat_profiles cp
      where cp.owner_auth_uid = auth.uid()
        and (cp.mc_profile_id = chat_friendships.profile_low or cp.mc_profile_id = chat_friendships.profile_high)
    )
  );

drop policy if exists chat_friend_requests_select_participant on public.chat_friend_requests;
create policy chat_friend_requests_select_participant
  on public.chat_friend_requests
  for select
  to authenticated
  using (
    exists (
      select 1
      from public.chat_profiles cp
      where cp.owner_auth_uid = auth.uid()
        and (cp.mc_profile_id = chat_friend_requests.sender_profile_id or cp.mc_profile_id = chat_friend_requests.receiver_profile_id)
    )
  );

drop policy if exists chat_friend_requests_insert_sender on public.chat_friend_requests;
create policy chat_friend_requests_insert_sender
  on public.chat_friend_requests
  for insert
  to authenticated
  with check (
    exists (
      select 1
      from public.chat_profiles cp
      where cp.owner_auth_uid = auth.uid()
        and cp.mc_profile_id = chat_friend_requests.sender_profile_id
    )
  );

drop policy if exists chat_friend_requests_update_participant on public.chat_friend_requests;
create policy chat_friend_requests_update_participant
  on public.chat_friend_requests
  for update
  to authenticated
  using (
    exists (
      select 1
      from public.chat_profiles cp
      where cp.owner_auth_uid = auth.uid()
        and (cp.mc_profile_id = chat_friend_requests.sender_profile_id or cp.mc_profile_id = chat_friend_requests.receiver_profile_id)
    )
  )
  with check (
    exists (
      select 1
      from public.chat_profiles cp
      where cp.owner_auth_uid = auth.uid()
        and (cp.mc_profile_id = chat_friend_requests.sender_profile_id or cp.mc_profile_id = chat_friend_requests.receiver_profile_id)
    )
  );

drop policy if exists chat_notifications_select_own on public.chat_notifications;
create policy chat_notifications_select_own
  on public.chat_notifications
  for select
  to authenticated
  using (
    exists (
      select 1
      from public.chat_profiles cp
      where cp.owner_auth_uid = auth.uid()
        and cp.mc_profile_id = chat_notifications.profile_id
    )
  );

drop policy if exists chat_notifications_update_own on public.chat_notifications;
create policy chat_notifications_update_own
  on public.chat_notifications
  for update
  to authenticated
  using (
    exists (
      select 1
      from public.chat_profiles cp
      where cp.owner_auth_uid = auth.uid()
        and cp.mc_profile_id = chat_notifications.profile_id
    )
  )
  with check (
    exists (
      select 1
      from public.chat_profiles cp
      where cp.owner_auth_uid = auth.uid()
        and cp.mc_profile_id = chat_notifications.profile_id
    )
  );

grant select, insert, update on public.chat_profiles to authenticated;
grant select, insert, update on public.chat_presence to authenticated;
grant select on public.chat_threads to authenticated;
grant select on public.chat_thread_members to authenticated;
grant select, insert, update on public.chat_messages to authenticated;
grant select, insert, delete on public.chat_message_reactions to authenticated;
grant select, insert, update on public.chat_read_receipts to authenticated;
grant select, insert, update, delete on public.chat_typing_states to authenticated;
grant select on public.chat_friendships to authenticated;
grant select, insert, update on public.chat_friend_requests to authenticated;
grant select, update on public.chat_notifications to authenticated;
grant usage, select on sequence public.chat_messages_id_seq to authenticated;
grant usage, select on sequence public.chat_notifications_id_seq to authenticated;

grant execute on function public.chat_actor_profile_id() to authenticated;
grant execute on function public.chat_sync_identity(text, text, text) to authenticated;
grant execute on function public.chat_set_presence(boolean) to authenticated;
grant execute on function public.chat_search_profiles(text, integer) to authenticated;
grant execute on function public.chat_create_dm(text) to authenticated;
grant execute on function public.chat_create_group(text, text[]) to authenticated;
grant execute on function public.chat_list_threads() to authenticated;
grant execute on function public.chat_list_messages(uuid, integer) to authenticated;
grant execute on function public.chat_list_members(uuid) to authenticated;
grant execute on function public.chat_list_reactions(uuid) to authenticated;
grant execute on function public.chat_list_typing(uuid) to authenticated;
grant execute on function public.chat_mark_thread_read(uuid, bigint) to authenticated;
grant execute on function public.chat_set_typing(uuid, boolean) to authenticated;
grant execute on function public.chat_run_maintenance() to authenticated;
grant execute on function public.chat_send_friend_request(text) to authenticated;
grant execute on function public.chat_respond_friend_request(uuid, text) to authenticated;
grant execute on function public.chat_list_friend_requests() to authenticated;
grant execute on function public.chat_list_friends() to authenticated;
grant execute on function public.chat_list_notifications(integer) to authenticated;
grant execute on function public.chat_mark_notifications_read(bigint) to authenticated;

alter table public.chat_threads replica identity full;
alter table public.chat_thread_members replica identity full;
alter table public.chat_messages replica identity full;
alter table public.chat_message_reactions replica identity full;
alter table public.chat_read_receipts replica identity full;
alter table public.chat_typing_states replica identity full;
alter table public.chat_presence replica identity full;
alter table public.chat_friend_requests replica identity full;
alter table public.chat_friendships replica identity full;
alter table public.chat_notifications replica identity full;

do $$
declare
  tbl text;
begin
  if exists (select 1 from pg_publication where pubname = 'supabase_realtime') then
    foreach tbl in array array[
      'chat_threads',
      'chat_thread_members',
      'chat_messages',
      'chat_message_reactions',
      'chat_read_receipts',
      'chat_typing_states',
      'chat_presence',
      'chat_profiles',
      'chat_friendships',
      'chat_friend_requests',
      'chat_notifications'
    ]
    loop
      if not exists (
        select 1
        from pg_publication_tables ppt
        where ppt.pubname = 'supabase_realtime'
          and ppt.schemaname = 'public'
          and ppt.tablename = tbl
      ) then
        execute format('alter publication supabase_realtime add table public.%I', tbl);
      end if;
    end loop;
  else
    raise notice 'supabase_realtime publication not found; realtime table registration skipped.';
  end if;
end $$;

do $$
declare
  existing_job record;
begin
  if exists (select 1 from pg_extension where extname = 'pg_cron') then
    for existing_job in
      select j.jobid
      from cron.job j
      where j.jobname = 'chat_maintenance_10m'
    loop
      perform cron.unschedule(existing_job.jobid);
    end loop;

    perform cron.schedule(
      'chat_maintenance_10m',
      '*/10 * * * *',
      $cron$select public.chat_run_maintenance();$cron$
    );
  else
    raise notice 'pg_cron extension unavailable. Run SELECT public.chat_run_maintenance(); periodically.';
  end if;
end $$;

commit;
